name: Clean, build, test, coverage

on:
  push:
    branches:
      - master
      - develop
      - task/PSGS-57-missing-apis-proxy
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load Variables
        id: load_envvars
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_1_PASSPHRASE=${{ secrets.CARDANO_API_WALLET_1_PASSPHRASE }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_1_MNEMONIC=${{ secrets.CARDANO_API_WALLET_1_MNEMONIC }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_2_MNEMONIC=${{ secrets.CARDANO_API_WALLET_2_MNEMONIC }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_3_MNEMONIC=${{ secrets.CARDANO_API_WALLET_3_MNEMONIC }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_3_MNEMONIC_SECONDARY=${{ secrets.CARDANO_API_WALLET_3_MNEMONIC_SECONDARY }}" >> $GITHUB_ENV
          echo "CARDANO_API_WALLET_3_PASSPHRASE=${{ secrets.CARDANO_API_WALLET_3_PASSPHRASE }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.0.8'
      - run: sbt coverage test it:test coverageReport
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/scala-2.13/scoverage-report

